### ISSUE TITLE
Blog Redux Test Posts Tag not working

### ISSUE THREAD

**Issue by aayushmalik** [morskyjezek/jezek-site#2]
Hi Jesse,

Did you figure out a way of hyperlinking the tags on [this page](https://github.com/morskyjezek/jezek-site/blob/main/_pages/blog-redux-test.html) to the relevant posts just like it works for the years section?

I was trying to do something similar for my minimal-mistakes site and I am stuck at the same point.

Best,

**Comment by aayushmalik** [comment]
Until then, I have found a work-around and I am using [this](https://aayushmalik.github.io/posts/)

**Comment by morskyjezek** [comment]
No, I haven't really fixed that page, but I think it would be something similar to https://www.jesseajohnston.net/tags/ . I was considering using something like the categories layout - https://github.com/morskyjezek/jezek-site/blob/main/_layouts/categories.html .

**Comment by morskyjezek** [comment]
That's a good work-around, thanks for sharing it!

**Comment by morskyjezek** [comment]
This is addressed by adding the following to the page metadata:

layout: posts
entries_layout: grid

I've done that in this commit 810f46ba3e51cb3cc97c828900b74355df94a967 and should display at the /blog-dev/ url
